"""Voice capture interview prompt library.

95+ prompts across 9 categories, drawn from proven content frameworks:
- Dickie Bush / Nicolas Cole (4A Framework, Endless Idea Generator)
- PipDecks (Storyteller Tactics)
- StoryBrand (Donald Miller's SB7)
- Matthew Dicks (Storyworthy, First/Last/Best/Worst)
- Justin Welsh (Content Matrix)
- SME Interview Frameworks
- Jay Acunzo (Signature Story)
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Category metadata
# ---------------------------------------------------------------------------

CATEGORIES: dict[str, dict] = {
    "warmup": {
        "name": "Warmup & Identity",
        "description": "Let's start easy. These help establish who you are and what you do.",
        "estimated_minutes": 5,
        "order": 1,
    },
    "origin_story": {
        "name": "Your Origin Story",
        "description": "How did you get here? These questions surface your journey and pivotal moments.",
        "estimated_minutes": 15,
        "order": 2,
    },
    "expertise": {
        "name": "Your Expertise & Method",
        "description": "What do you know that others don't? Walk us through your frameworks and processes.",
        "estimated_minutes": 15,
        "order": 3,
    },
    "client_stories": {
        "name": "Client Stories & Wins",
        "description": "Your clients' transformations are your best content. Let's capture them.",
        "estimated_minutes": 15,
        "order": 4,
    },
    "problems": {
        "name": "Problems & Pain Points",
        "description": "What does your audience struggle with? Let's go deep on the pain you solve.",
        "estimated_minutes": 10,
        "order": 5,
    },
    "contrarian": {
        "name": "Contrarian Views & Hot Takes",
        "description": "Your strongest opinions make the best content. Don't hold back.",
        "estimated_minutes": 10,
        "order": 6,
    },
    "teaching": {
        "name": "Teaching Moments",
        "description": "If you could teach the world one thing, what would it be? Let's capture your lessons.",
        "estimated_minutes": 15,
        "order": 7,
    },
    "vision": {
        "name": "Vision & Values",
        "description": "Why do you do this work? What's the bigger picture?",
        "estimated_minutes": 10,
        "order": 8,
    },
    "quickfire": {
        "name": "Quick-Fire Round",
        "description": "Short, punchy answers. Don't overthink — just say what comes to mind first.",
        "estimated_minutes": 5,
        "order": 9,
    },
}

# ---------------------------------------------------------------------------
# Prompt library
# ---------------------------------------------------------------------------

PROMPT_LIBRARY: list[dict] = [
    # ── Category 1: Warmup & Identity ──────────────────────────────────────
    {
        "id": "warmup_01",
        "category": "warmup",
        "question": "What's your name and what do you do?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "story",
        "estimated_minutes": 1,
        "tags": ["personal_branding"],
    },
    {
        "id": "warmup_02",
        "category": "warmup",
        "question": "How do you explain what you do to someone at a dinner party?",
        "follow_up": "What's the reaction you usually get?",
        "framework": "storybrand",
        "content_type": "story",
        "estimated_minutes": 1,
        "tags": ["personal_branding"],
    },
    {
        "id": "warmup_03",
        "category": "warmup",
        "question": "What would your clients say you do for them?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "testimonial",
        "estimated_minutes": 1,
        "tags": ["personal_branding"],
    },
    {
        "id": "warmup_04",
        "category": "warmup",
        "question": "If you had a professional tagline, what would it be?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "story",
        "estimated_minutes": 1,
        "tags": ["personal_branding"],
    },
    {
        "id": "warmup_05",
        "category": "warmup",
        "question": "What's one thing people are always surprised to learn about you?",
        "follow_up": None,
        "framework": "dicks",
        "content_type": "story",
        "estimated_minutes": 1,
        "tags": ["personal_branding"],
    },
    # ── Category 2: Origin Story ───────────────────────────────────────────
    {
        "id": "origin_01",
        "category": "origin_story",
        "question": "How did you find your way into this work?",
        "follow_up": "Was there a specific event or person that led you here?",
        "framework": "sme",
        "content_type": "story",
        "estimated_minutes": 3,
        "tags": ["career_transition"],
    },
    {
        "id": "origin_02",
        "category": "origin_story",
        "question": "What were you doing before this, and what made you switch?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["career_transition"],
    },
    {
        "id": "origin_03",
        "category": "origin_story",
        "question": "What was the moment you realized this was what you were meant to do?",
        "follow_up": "What were you doing right before that moment?",
        "framework": "dicks",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["career_transition", "mindset"],
    },
    {
        "id": "origin_04",
        "category": "origin_story",
        "question": "Tell me about a time you almost gave up on this path. What kept you going?",
        "follow_up": None,
        "framework": "pipdecks",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["mindset", "confidence"],
    },
    {
        "id": "origin_05",
        "category": "origin_story",
        "question": "What's the first time you helped someone with this and realized you were actually good at it?",
        "follow_up": "What did that feel like?",
        "framework": "dicks",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["confidence"],
    },
    {
        "id": "origin_06",
        "category": "origin_story",
        "question": "What did you wish you knew when you were starting out?",
        "follow_up": None,
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 1,
        "tags": ["mindset"],
    },
    {
        "id": "origin_07",
        "category": "origin_story",
        "question": "Who influenced you the most in how you approach this work?",
        "follow_up": "What specifically did they teach you or model for you?",
        "framework": "pipdecks",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["mindset"],
    },
    {
        "id": "origin_08",
        "category": "origin_story",
        "question": "What's the hardest lesson your career has taught you?",
        "follow_up": None,
        "framework": "cole",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["mindset"],
    },
    {
        "id": "origin_09",
        "category": "origin_story",
        "question": "What failure taught you the most?",
        "follow_up": "How did it change the way you work?",
        "framework": "dicks",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["mindset", "rejection_handling"],
    },
    {
        "id": "origin_10",
        "category": "origin_story",
        "question": "If you could go back and tell your younger self one thing about this career, what would it be?",
        "follow_up": None,
        "framework": "bush",
        "content_type": "story",
        "estimated_minutes": 1,
        "tags": ["mindset"],
    },
    # ── Category 3: Expertise & Method ─────────────────────────────────────
    {
        "id": "expertise_01",
        "category": "expertise",
        "question": "Walk me through your process when a new client comes to you. Step by step, from the first conversation to the end result.",
        "follow_up": None,
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 3,
        "tags": ["job_search_strategy"],
    },
    {
        "id": "expertise_02",
        "category": "expertise",
        "question": "What's the framework or system you've developed that you're most proud of?",
        "follow_up": "Walk me through how it works.",
        "framework": "bush",
        "content_type": "playbook",
        "estimated_minutes": 3,
        "tags": ["job_search_strategy"],
    },
    {
        "id": "expertise_03",
        "category": "expertise",
        "question": "Explain what you do like I'm five years old.",
        "follow_up": None,
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 1,
        "tags": ["personal_branding"],
    },
    {
        "id": "expertise_04",
        "category": "expertise",
        "question": "What are the three most important things someone needs to understand about your field?",
        "follow_up": None,
        "framework": "bush",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "expertise_05",
        "category": "expertise",
        "question": "What tools or resources do you recommend to everyone you work with?",
        "follow_up": "Why those specifically?",
        "framework": "cole",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": ["ai_tools"],
    },
    {
        "id": "expertise_06",
        "category": "expertise",
        "question": "How do you know when something is working versus when it's not?",
        "follow_up": "What are the early warning signs?",
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "expertise_07",
        "category": "expertise",
        "question": "What does your typical engagement or project look like from start to finish?",
        "follow_up": "What's the timeline, and what are the milestones?",
        "framework": "bush",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "expertise_08",
        "category": "expertise",
        "question": "What's the first thing you assess when you start working with someone new?",
        "follow_up": None,
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "expertise_09",
        "category": "expertise",
        "question": "What patterns do you see across all your most successful clients or projects?",
        "follow_up": "What do they have in common?",
        "framework": "bush",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "expertise_10",
        "category": "expertise",
        "question": "What's your secret weapon — the thing that sets you apart from others who do similar work?",
        "follow_up": None,
        "framework": "welsh",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["personal_branding"],
    },
    {
        "id": "expertise_11",
        "category": "expertise",
        "question": "What's the most underrated skill or tool in your industry?",
        "follow_up": "Why do people overlook it?",
        "framework": "cole",
        "content_type": "playbook",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "expertise_12",
        "category": "expertise",
        "question": "If someone could only do one thing to improve in your area, what should it be?",
        "follow_up": None,
        "framework": "bush",
        "content_type": "playbook",
        "estimated_minutes": 1,
        "tags": [],
    },
    # ── Category 4: Client Stories & Wins ──────────────────────────────────
    {
        "id": "client_01",
        "category": "client_stories",
        "question": "Tell me about your proudest client success story. What was their situation before, and what happened after working with you?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "testimonial",
        "estimated_minutes": 3,
        "tags": [],
    },
    {
        "id": "client_02",
        "category": "client_stories",
        "question": "Describe a client who came to you feeling completely stuck. How did you help them break through?",
        "follow_up": "What was the turning point for them?",
        "framework": "pipdecks",
        "content_type": "testimonial",
        "estimated_minutes": 3,
        "tags": ["mindset"],
    },
    {
        "id": "client_03",
        "category": "client_stories",
        "question": "What's the biggest transformation you've ever helped someone achieve?",
        "follow_up": "Where did they start, and where did they end up?",
        "framework": "dicks",
        "content_type": "testimonial",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "client_04",
        "category": "client_stories",
        "question": "Tell me about a client who surprised you with what they accomplished.",
        "follow_up": "What did they do that you didn't expect?",
        "framework": "storybrand",
        "content_type": "testimonial",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "client_05",
        "category": "client_stories",
        "question": "What results do your clients typically see? Give me specific numbers, outcomes, or timeframes.",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "testimonial",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "client_06",
        "category": "client_stories",
        "question": "Tell me about a time a client almost didn't work with you, but then did — and what happened next.",
        "follow_up": None,
        "framework": "cole",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "client_07",
        "category": "client_stories",
        "question": "What do your clients say about working with you? Try to quote them in their own words.",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "testimonial",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "client_08",
        "category": "client_stories",
        "question": "Describe a project or engagement that didn't go as planned. What did you learn from it?",
        "follow_up": None,
        "framework": "pipdecks",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["rejection_handling"],
    },
    {
        "id": "client_09",
        "category": "client_stories",
        "question": "What's the most common 'aha moment' your clients have while working with you?",
        "follow_up": "What usually triggers it?",
        "framework": "sme",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["mindset"],
    },
    {
        "id": "client_10",
        "category": "client_stories",
        "question": "If one of your past clients were sitting here right now, what would they say was the single biggest turning point in your work together?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "testimonial",
        "estimated_minutes": 2,
        "tags": [],
    },
    # ── Category 5: Problems & Pain Points ─────────────────────────────────
    {
        "id": "problem_01",
        "category": "problems",
        "question": "What's the single biggest problem your clients come to you with?",
        "follow_up": "How do they usually describe it in their own words?",
        "framework": "storybrand",
        "content_type": "qa",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "problem_02",
        "category": "problems",
        "question": "How does that problem make your clients feel? What's the emotional toll of living with it?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": ["mindset"],
    },
    {
        "id": "problem_03",
        "category": "problems",
        "question": "Why is it wrong that people have to deal with this problem? What should be different about the world?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": ["mindset"],
    },
    {
        "id": "problem_04",
        "category": "problems",
        "question": "What's the cost of NOT solving this problem? What do people lose — money, time, opportunities, relationships?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "qa",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "problem_05",
        "category": "problems",
        "question": "What's the most common mistake people make when trying to solve this problem on their own?",
        "follow_up": "Why doesn't that approach work?",
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "problem_06",
        "category": "problems",
        "question": "What bad advice is floating around in your industry that you wish would stop?",
        "follow_up": "Where does it come from, and why is it harmful?",
        "framework": "cole",
        "content_type": "qa",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "problem_07",
        "category": "problems",
        "question": "What do people try first that doesn't work? And why doesn't it work?",
        "follow_up": None,
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "problem_08",
        "category": "problems",
        "question": "If you could wave a magic wand and fix one thing about your industry overnight, what would it be?",
        "follow_up": None,
        "framework": "sme",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "problem_09",
        "category": "problems",
        "question": "What question do people ask you more than any other?",
        "follow_up": "And what's your answer?",
        "framework": "sme",
        "content_type": "qa",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "problem_10",
        "category": "problems",
        "question": "What frustrates you the most about your industry right now?",
        "follow_up": None,
        "framework": "welsh",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": [],
    },
    # ── Category 6: Contrarian Views & Hot Takes ───────────────────────────
    {
        "id": "contrarian_01",
        "category": "contrarian",
        "question": "What's something you believe about your field that most people would disagree with?",
        "follow_up": "What experience led you to that belief?",
        "framework": "acunzo",
        "content_type": "qa",
        "estimated_minutes": 2,
        "tags": ["mindset"],
    },
    {
        "id": "contrarian_02",
        "category": "contrarian",
        "question": "What popular advice in your industry is actually harmful?",
        "follow_up": "What should people do instead?",
        "framework": "cole",
        "content_type": "qa",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "contrarian_03",
        "category": "contrarian",
        "question": "What's a trend everyone is excited about that you think is overrated?",
        "follow_up": "Why?",
        "framework": "welsh",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "contrarian_04",
        "category": "contrarian",
        "question": "What's the uncomfortable truth about your industry that nobody wants to talk about?",
        "follow_up": None,
        "framework": "bush",
        "content_type": "qa",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "contrarian_05",
        "category": "contrarian",
        "question": "What conventional wisdom did you have to unlearn to get where you are?",
        "follow_up": "What replaced it?",
        "framework": "dicks",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["mindset"],
    },
    {
        "id": "contrarian_06",
        "category": "contrarian",
        "question": "Is there something your industry does 'because we've always done it that way' that desperately needs to change?",
        "follow_up": None,
        "framework": "sme",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "contrarian_07",
        "category": "contrarian",
        "question": "What would you change about how your profession is taught or practiced?",
        "follow_up": None,
        "framework": "welsh",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "contrarian_08",
        "category": "contrarian",
        "question": "What hill will you die on professionally?",
        "follow_up": "Why does this matter so much to you?",
        "framework": "cole",
        "content_type": "qa",
        "estimated_minutes": 2,
        "tags": ["mindset"],
    },
    # ── Category 7: Teaching Moments ───────────────────────────────────────
    {
        "id": "teaching_01",
        "category": "teaching",
        "question": "What are the three biggest mistakes beginners make in your field?",
        "follow_up": "What should they do instead?",
        "framework": "cole",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "teaching_02",
        "category": "teaching",
        "question": "Walk me through how you would teach someone your single most important concept from scratch.",
        "follow_up": None,
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 3,
        "tags": [],
    },
    {
        "id": "teaching_03",
        "category": "teaching",
        "question": "What's a simple daily or weekly habit that would transform how people approach your area of expertise?",
        "follow_up": None,
        "framework": "cole",
        "content_type": "playbook",
        "estimated_minutes": 1,
        "tags": ["time_management"],
    },
    {
        "id": "teaching_04",
        "category": "teaching",
        "question": "Tell me about a lesson you learned the hard way — one that cost you time, money, or pain.",
        "follow_up": "What would you do differently now?",
        "framework": "dicks",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["mindset"],
    },
    {
        "id": "teaching_05",
        "category": "teaching",
        "question": "What's the one thing that takes people from good to great in your field?",
        "follow_up": None,
        "framework": "bush",
        "content_type": "playbook",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "teaching_06",
        "category": "teaching",
        "question": "If you had five minutes to teach someone the most important thing you know, what would you say?",
        "follow_up": None,
        "framework": "sme",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "teaching_07",
        "category": "teaching",
        "question": "What's a small change that makes a disproportionately big difference in your field?",
        "follow_up": "Why does something so small have such a big impact?",
        "framework": "pipdecks",
        "content_type": "playbook",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "teaching_08",
        "category": "teaching",
        "question": "What do people overcomplicate that's actually simple when you break it down?",
        "follow_up": "Break it down for me right now.",
        "framework": "cole",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "teaching_09",
        "category": "teaching",
        "question": "What do people think is simple that's actually much more nuanced than it appears?",
        "follow_up": "What are the hidden layers?",
        "framework": "bush",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "teaching_10",
        "category": "teaching",
        "question": "What's the checklist, mental model, or decision-making framework you use most in your work?",
        "follow_up": "Walk me through a real example of using it.",
        "framework": "bush",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "teaching_11",
        "category": "teaching",
        "question": "What books, tools, or people completely changed how you think about your work?",
        "follow_up": "What specifically did you take from them?",
        "framework": "cole",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "teaching_12",
        "category": "teaching",
        "question": "What's your favorite analogy or metaphor for explaining a complex concept in your field?",
        "follow_up": "Use it right now — explain that concept to me.",
        "framework": "pipdecks",
        "content_type": "playbook",
        "estimated_minutes": 2,
        "tags": [],
    },
    # ── Category 8: Vision & Values ────────────────────────────────────────
    {
        "id": "vision_01",
        "category": "vision",
        "question": "Why do you do this work? What drives you beyond the paycheck?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": ["mindset"],
    },
    {
        "id": "vision_02",
        "category": "vision",
        "question": "What change do you want to see in the world through your work?",
        "follow_up": None,
        "framework": "pipdecks",
        "content_type": "story",
        "estimated_minutes": 1,
        "tags": ["mindset"],
    },
    {
        "id": "vision_03",
        "category": "vision",
        "question": "What does success look like for you in five years?",
        "follow_up": "Not just professionally — what does the whole picture look like?",
        "framework": "sme",
        "content_type": "story",
        "estimated_minutes": 2,
        "tags": [],
    },
    {
        "id": "vision_04",
        "category": "vision",
        "question": "What kind of clients do you absolutely love working with, and why?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "vision_05",
        "category": "vision",
        "question": "What kind of clients are NOT a good fit for you? Who should not hire you?",
        "follow_up": None,
        "framework": "welsh",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": [],
    },
    {
        "id": "vision_06",
        "category": "vision",
        "question": "What legacy do you want to leave in your field?",
        "follow_up": None,
        "framework": "bush",
        "content_type": "story",
        "estimated_minutes": 1,
        "tags": ["mindset"],
    },
    {
        "id": "vision_07",
        "category": "vision",
        "question": "What's possible now in your field that wasn't possible five years ago?",
        "follow_up": "What excites you most about that?",
        "framework": "welsh",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": ["ai_tools"],
    },
    {
        "id": "vision_08",
        "category": "vision",
        "question": "If you could guarantee one outcome for every person who works with you, what would it be?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "qa",
        "estimated_minutes": 1,
        "tags": [],
    },
    # ── Category 9: Quick-Fire Round ───────────────────────────────────────
    {
        "id": "quickfire_01",
        "category": "quickfire",
        "question": "Best professional advice you ever received?",
        "follow_up": None,
        "framework": "dicks",
        "content_type": "qa",
        "estimated_minutes": 0.5,
        "tags": [],
    },
    {
        "id": "quickfire_02",
        "category": "quickfire",
        "question": "Worst advice you were ever given?",
        "follow_up": None,
        "framework": "dicks",
        "content_type": "qa",
        "estimated_minutes": 0.5,
        "tags": [],
    },
    {
        "id": "quickfire_03",
        "category": "quickfire",
        "question": "A book or resource that changed everything for you?",
        "follow_up": None,
        "framework": "cole",
        "content_type": "qa",
        "estimated_minutes": 0.5,
        "tags": [],
    },
    {
        "id": "quickfire_04",
        "category": "quickfire",
        "question": "Your first big professional win?",
        "follow_up": None,
        "framework": "dicks",
        "content_type": "story",
        "estimated_minutes": 0.5,
        "tags": [],
    },
    {
        "id": "quickfire_05",
        "category": "quickfire",
        "question": "Your most recent win?",
        "follow_up": None,
        "framework": "dicks",
        "content_type": "story",
        "estimated_minutes": 0.5,
        "tags": [],
    },
    {
        "id": "quickfire_06",
        "category": "quickfire",
        "question": "One word that describes your approach to work?",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "qa",
        "estimated_minutes": 0.5,
        "tags": ["personal_branding"],
    },
    {
        "id": "quickfire_07",
        "category": "quickfire",
        "question": "What would you tell someone on their very first day in your field?",
        "follow_up": None,
        "framework": "cole",
        "content_type": "qa",
        "estimated_minutes": 0.5,
        "tags": [],
    },
    {
        "id": "quickfire_08",
        "category": "quickfire",
        "question": "The project or client you're most proud of?",
        "follow_up": None,
        "framework": "dicks",
        "content_type": "testimonial",
        "estimated_minutes": 0.5,
        "tags": [],
    },
    {
        "id": "quickfire_09",
        "category": "quickfire",
        "question": "Something about your work that brings you pure joy?",
        "follow_up": None,
        "framework": "pipdecks",
        "content_type": "story",
        "estimated_minutes": 0.5,
        "tags": ["mindset"],
    },
    {
        "id": "quickfire_10",
        "category": "quickfire",
        "question": "Finish this sentence: 'I help people ___.'",
        "follow_up": None,
        "framework": "storybrand",
        "content_type": "qa",
        "estimated_minutes": 0.5,
        "tags": ["personal_branding"],
    },
]


# ---------------------------------------------------------------------------
# Access functions
# ---------------------------------------------------------------------------

def get_prompts_by_category(category: str) -> list[dict]:
    """Get all prompts for a given category slug."""
    return [p for p in PROMPT_LIBRARY if p["category"] == category]


def get_all_prompts() -> list[dict]:
    """Get all prompts in session order (sorted by category order, then by id)."""
    cat_order = {k: v["order"] for k, v in CATEGORIES.items()}
    return sorted(PROMPT_LIBRARY, key=lambda p: (cat_order.get(p["category"], 99), p["id"]))


def get_prompt_count() -> int:
    """Get total number of prompts in the library."""
    return len(PROMPT_LIBRARY)


def get_category_counts() -> dict[str, int]:
    """Get prompt counts per category."""
    counts: dict[str, int] = {}
    for p in PROMPT_LIBRARY:
        counts[p["category"]] = counts.get(p["category"], 0) + 1
    return counts


# ---------------------------------------------------------------------------
# Niche prompt generation
# ---------------------------------------------------------------------------

NICHE_GENERATION_SYSTEM = """You are a content strategist helping build a voice capture interview guide.

Given a professional niche/industry, generate targeted interview questions that will surface rich, specific content from a subject matter expert in that field.

Rules:
- Generate exactly {count} questions
- Questions should be specific to the niche, not generic
- Mix of question types: stories, how-to, opinions, client examples
- Questions should elicit answers that work well as LinkedIn posts, newsletters, or video scripts
- Each question should be different from the universal questions provided
- Return JSON array of objects with keys: question, follow_up (string or null), content_type (qa/playbook/story/testimonial), tags (list of strings)"""

NICHE_GENERATION_USER = """Niche/Industry: {niche}

Here are the universal questions already in the guide (don't duplicate these):
{existing_questions}

Generate {count} niche-specific questions for this professional. Return valid JSON only."""
